on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Configure gradle
        run: ./gradlew

      - name: Build with gradle
        run: ./gradlew verifyPlugin build

      - name: Prepare artifact upload
        run: |
          file_count=$(ls build/distributions/*.zip | wc -l)
          if ! [[ $file_count -eq 1 ]]; then
            echo "Expected exactly one ZIP file in build/distributions!"
            exit 1
          fi

          mv build/distributions/*.zip FreeMaterialThemePlugin.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Plugin distribution
          path: FreeMaterialThemePlugin.zip
